[project]
name = "agentsouschef"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.123.5",
    "openai>=2.8.1",
    "streamlit>=1.51.0",
    "uvicorn>=0.38.0",
]
